### ISSUE TITLE
Disable jenkins plugins autoupdate when restart jenkins

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ee-ops#650]
Same issue https://community.jenkins.io/t/disable-auto-update-of-jenkins-and-jenkins-plugins-when-restarting-jenkins/1662.

Possible sulution  https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#consider-using-a-custom-image.

**Comment by wuhuizuo** [comment]
Fixed.
Ref: https://github.com/PingCAP-QE/ee-ops/blob/8e20e63d62dd5cd93206a0f7f2871f7dcdcc577a/apps/prod/jenkins-beta/release/values-controller-plugins.yaml#L14
