### ISSUE TITLE
jenkins ui-test pod use the wrong image tag

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ee-ops#661]
<img width="864" alt="image" src="https://github.com/PingCAP-QE/ee-ops/assets/16618216/d75f69d7-a338-4dad-b8b0-f22751c3d393">
If we try to use an image built from the internal mirror repository, there may be cases where the image does not exist due to improper tag settings.

**Comment by wuhuizuo** [comment]
It's copied from other image, and it is done in init containers, it's not a bug.
